### ISSUE TITLE
Pipeline is slow and times out

### ISSUE THREAD

**Issue by ktk** [zazuko/amos#46]
@PlekszyGladz ok I've fixed the pipeline, problem was the XML file in git, this kills Gitlab somehow. In other words we cannot store the XML in the git repo anymore, at least not uncompressed.

Now it fails here:

```
Error: error in forEach sub-pipeline urn:pipeline:amos#TransformCsv
    at ForEach._write (file:///Users/ktk/workspace/zazuko/amos/node_modules/barnard59-base/forEach.js:64:19)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
Caused by: Error: Unknown language: dt. 
 Please redefine your languageMap
    at splitLanguages (file:///Users/ktk/workspace/zazuko/amos/lib/languages.js:39:13)
    at Object.transformQuads (file:///Users/ktk/workspace/zazuko/amos/lib/quads.js:8:19)
    at file:///Users/ktk/workspace/zazuko/amos/node_modules/barnard59-base/map.js:8:21
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
Error: error in forEach sub-pipeline urn:pipeline:amos#TransformCsv
    at ForEach._write (file:///Users/ktk/workspace/zazuko/amos/node_modules/barnard59-base/forEach.js:64:19)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
Caused by: Error: Unknown language: dt. 
 Please redefine your languageMap
    at splitLanguages (file:///Users/ktk/workspace/zazuko/amos/lib/languages.js:39:13)
    at Object.transformQuads (file:///Users/ktk/workspace/zazuko/amos/lib/quads.js:8:19)
    at file:///Users/ktk/workspace/zazuko/amos/node_modules/barnard59-base/map.js:8:21
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)

```

I had that for spanish as well and I added a new entry in the Turtle-File but I guess here it needs data alignment? I guess dt is deutsch.

**Comment by PlekszyGladz** [comment]
@ktk yes 'dt' is 'deutsch'. I tried to implement this [here](https://gitlab.zazuko.com/amos/amos/-/commit/b9ed9f5e3c2daa61cca2ead8bbd133dfeb1a33aa). It seems to work fine but it's rather hacky and hardcoded atm...

**Comment by PlekszyGladz** [comment]
current state of this issue:
- the mapping seems to work well atm. 
- also the pipeline runs 
- however it takes longer than the timeout (currently 1h). 
- @ktk we should soon investigate why the process is so slow!

**Comment by l00mi** [comment]
It is working now, and does not timeout.
